li_gen/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers

from . import views

app_name = 'li_gen'

router = routers.DefaultRouter()
router.register('categories', views.CategoryViewSet)
router.register('licenses', views.LicenseViewSet)

urlpatterns = [
    path('', views.index, name='index'),
    path('license/', include('license.urls'), name='license'),
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
]

license/urls.py
from django.urls import path

from . import views

app_name = 'license'

urlpatterns = [
    path('', views.LicenseView.as_view(), name='index'),
]

api/models.py
from django.db import models  # noqa

# Create your models here.

li_gen/models.py
from functools import total_ordering

from peewee import CharField, Model, TextField

from .config import Config


@total_ordering
class License(Model):
    name = CharField()
    text = TextField()

    class Meta:
        database = Config.db

    def __eq__(self, other):
        return self.name == other.name

    def __lt__(self, other):
        return self.name < other.name

    def __str__(self):
        return self.name

license/models.py
from django.db import models
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    def __repr__(self):
        return f'<License: {str(self)}>'


class License(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    version = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    text = models.TextField()
    details = models.URLField(max_length=255)

    def save(self, *args, **kwargs):
        self.slug = slugify(f'{self.category.name}-{self.title}')
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.category.name} {self.title}'

    def __repr__(self):
        return f'<License: {str(self)}>'

api/views.py
def index(license: str, version: str):
    return f'<h1>{license}: {version}</h1>'

li_gen/views.py
from django.shortcuts import render
from rest_framework import permissions, viewsets

from license.models import Category, License
from license.serializers import CategorySerializer, LicenseSerializer


class CategoryViewSet(viewsets.ModelViewSet):
    queryset = Category.objects.all().order_by('name')
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    serializer_class = CategorySerializer


class LicenseViewSet(viewsets.ModelViewSet):
    queryset = License.objects.all().order_by('title')
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    serializer_class = LicenseSerializer


def index(request):
    return render(request, 'index.html')

license/views.py
from datetime import datetime

from django.http import HttpResponse
from django.shortcuts import render
from django.template import Context, Template
from django.views.generic import TemplateView

from .models import License


class LicenseView(TemplateView):
    def get(self, request):
        return render(request, 'license/index.html', {'licenses': License.objects.all(), 'year': datetime.now().year})

    def post(self, request):
        license_template = Template(f'<pre>{License.objects.get(slug=request.POST["license"]).text}</pre>')
        context = Context({k: v for k, v in request.POST.items() if not k == 'license'})
        return HttpResponse(license_template.render(context))

li_gen/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang='en'>
  <head>
    <title>LiGen</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'license/css/main.css' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <div class="container-fluid">
      <h1>LiGen</h1>
      <p>License infrastructure is boring and you have better things to be doing, let us handle it, and just <a href='{% url 'license:index' %}'>create your file!</a></p>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

license/templates/license/index.html
{% load static %}

<!DOCTYPE html>
<html lang='en'>
  <head>
    <title>LiGen</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'license/css/main.css' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <div class="container-fluid">
      <h1>LiGen</h1>
      <form action='{% url 'license:index' %}' method='POST'>
        {% csrf_token %}
        <label for='project_name' class="label">Project Name:</label>
        <input type='text' name='project_name' class="text"/>
        <br/>

        <label for='author_name' class="label">Author Name:</label>
        <input type='text' name='copyright_holder' class="text"/>
        <br/>

        <label for='author_email' class="label">Author Email:</label>
        <input type='text' name='email' class="text"/>
        <br/>

        <label for='license' class="label">License:</label>
        <select name='license' class="text">
          {% for license in licenses %}
          <option name='license'>{{ license.slug }}</option>
          {% endfor %}
        </select>
        <br/>

        <input type='hidden' value='{{ year }}' name='year'>

        <input type='submit' value='Create License'/>
      </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>